### ISSUE TITLE
suggestion : possibility to display at the bottom to avoid hiding flags

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [phu54321/anki_plugins#14] opened 2019-11-27 11:02 UTC
Thanks :) !

**Comment by phu54321** [comment] 2019-11-27 11:03
what addon is this issue referring to?

**Comment by thiswillbeyourgithub** [comment] 2019-11-27 19:27
Progress bar addon, sorry

**Comment by thiswillbeyourgithub** [comment] 2020-03-09 11:11
related to #15

**Comment by phu54321** [comment] 2020-03-18 02:45
Duplicate of #15. Fixed

**Closed as completed by phu54321** 2020-03-18 02:45 UTC
Labels: Remaining Time
