### ISSUE TITLE
if we hide entire picture using Cloze (Hide All) won't hide the picture, is there any possibility to fix this , like Anki cloze? 

### ISSUE THREAD

**Issue by kaharjan** [phu54321/anki_plugins#34] opened 2020-04-23 11:45 UTC
I hide all three entire picture, as shown below: 
![image](https://user-images.githubusercontent.com/3367646/80095436-802b4a80-859a-11ea-9a8c-78ecd537717e.png)

but the result is:
![image](https://user-images.githubusercontent.com/3367646/80095386-6ab62080-859a-11ea-8462-04c6b1c2645a.png)
If we want to hide all of them, it seems don't work. thank you!

**Comment by phu54321** [comment] 2020-04-23 11:46
Duplicate of https://github.com/trgkanki/cloze_hide_all/issues/2

All repo moved there. Please report new issues at respective repos.
Thanks :)

**Closed as completed by phu54321** 2020-04-23 11:46 UTC
