### ISSUE TITLE
Cloze (Hide All) throwing error in browser in Anki 2.1.20beta2

### ISSUE THREAD

**Issue by ghost** [phu54321/anki_plugins#18] opened 2020-01-22 06:44 UTC
Debug info:
Anki 2.1.20 (c9a46268) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 359, in handler
  File "aqt\editor.py", line 442, in <lambda>
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1709973686\cloze_hide_all_21.py", line 417, in newCallback
    callback()
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-130>", line 2, in _closeWindow
  File "lib\site-packages\anki\hooks.py", line 480, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 475, in repl
  File "aqt\browser.py", line 694, in _closeWindow
  File "aqt\main.py", line 631, in maybeReset
  File "aqt\main.py", line 612, in reset
  File "aqt\gui_hooks.py", line 781, in __call__
  File "lib\site-packages\anki\hooks.py", line 425, in runHook
  File "aqt\modelchooser.py", line 47, in onReset
  File "aqt\modelchooser.py", line 93, in updateModels
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

**Comment by phu54321** [comment] 2020-03-09 04:55
Will fix till 03/11

**Comment by phu54321** [comment] 2020-03-11 09:38
Give me reproduction steps for this bug. Cannot reproduce with Anki 2.1.21
I changed cloze type cards to cloze-hide-all type, but no error.

Looking at the errored code I suspect this is not a bug of this addon, but rather a bug of that Anki version. (It's beta). Could you check if the bug is fixed on Anki 2.1.21?

**Comment by ghost** [comment] 2020-03-13 10:02
You're right. I couldn't reproduce any error.

**Comment by phu54321** [comment] 2020-03-13 11:41
tnahks for clarifying :)

**Closed as completed by phu54321** 2020-03-13 11:41 UTC
